[package]
name = "concrete-boolean"
version = "0.1.1"
edition = "2018"
authors = ["Zama team"]
license = "BSD-3-Clause-Clear"
description = "Homomorphic Boolean circuit interface for the concrete FHE library."
homepage = "https://crates.io/crates/concrete"
documentation = "https://docs.zama.ai/concrete/boolean-lib"
repository = "https://github.com/zama-ai/concrete"
readme = "README.md"
keywords = ["fully", "homomorphic", "encryption", "fhe", "cryptography"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"] }

[dependencies.concrete-core]
package = "concrete-core-experimental"
git = "https://github.com/zama-ai/concrete-core"
rev = "52084d47c8f5c98568b69389665e82baaf3b8790"
features = [
    "backend_default",
    "backend_default_serialization",
    "backend_default_parallel",
    "backend_default_generator_x86_64_aesni"
]

[dev-dependencies]
criterion = "0.3.4"
rand = "0.8.4"


[features]
default = ["fft"]
cuda = ["concrete-core/backend_cuda"]
fft = ["concrete-core/backend_fft"]
fftw = ["concrete-core/backend_fftw"]


[[bench]]
name = "bench"
harness = false

[package.metadata.docs.rs]
rustdoc-args = ["--html-in-header", "katex-header.html"]
