name: Cargo test concrete-boolean

# We test concrete-boolean in github actions and not on AWS
# as these tests are fast enough

on:
  push:
    paths:
      - 'concrete-boolean/**'

jobs:
  cargo-test-boolean:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Test concrete-boolean
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release -p concrete-boolean --all-targets
