# This job is the main jobs will dispatch build and test for every modules of our mono repo.
name: Main

on:
  pull_request:
  push:
    branches:
      - 'main'
    tags:
      - 'v[0-9]+.*'
  schedule:
    # Nightly Release @ 3AM after each work day
    - cron: "0 3 * * 2-6"

jobs:

#################################################
# Release jobs #################################
  concrete-python-nightly-release:
    uses: ./.github/workflows/start_slab.yml
    secrets: inherit
    with:
      command: concrete-python-release
      user_inputs: 'nightly'
